theme: jekyll-theme-minimal
title: notes.keiran.io
logo: https://avatars1.githubusercontent.com/u/1220700?s=460&v=4
description: Another attempt to consolidate some of my various published and presented content…